//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessia2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentInstallations
    {
        public int InstallationEquipmentID { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public int EmployeeID { get; set; }
        public int EquipmentID { get; set; }
        public int InstallitionAdressID { get; set; }
        public int SubscriberID { get; set; }
        public string ConnectionPoint { get; set; }
        public string GeographicCoordinates { get; set; }
        public string Notes { get; set; }
        public bool Rental { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual Subscribers Subscribers { get; set; }
    }
}
